const PDFDocument = require('pdfkit');

module.exports = async (sock, chatId, message, rawText) => {
    try {
        // Extract text from command (remove ".topdf " prefix)
        const pdfText = rawText.slice(6).trim();
        
        if (!pdfText) {
            await sock.sendMessage(chatId, {
                text: "📄 *PDF Converter*\n\nPlease provide text to convert to PDF\n\n*Example:* .topdf This is my text to convert\n.topdf Hello World!\n.topdf Convert this paragraph to PDF file"
            }, { quoted: message });
            return;
        }

        // Send processing reaction
        await sock.sendMessage(chatId, { 
            react: { text: '⏳', key: message.key } 
        });

        // Create PDF
        const pdfBuffer = await createPDF(pdfText);

        // Send the PDF file
        await sock.sendMessage(chatId, {
            document: pdfBuffer,
            mimetype: 'application/pdf',
            fileName: `document_${Date.now()}.pdf`,
            caption: "📄 *PDF created successfully!*\n\n🤖 *Powered by MAD-MAX*"
        }, { quoted: message });

        // Success reaction
        await sock.sendMessage(chatId, { 
            react: { text: '✅', key: message.key } 
        });

    } catch (error) {
        console.error('PDF creation error:', error);
        
        await sock.sendMessage(chatId, {
            text: "❌ Failed to create PDF. Please try again with different text."
        }, { quoted: message });

        await sock.sendMessage(chatId, { 
            react: { text: '❌', key: message.key } 
        });
    }
};

// Function to create PDF from text
async function createPDF(text) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({
                size: 'A4',
                margins: { top: 50, bottom: 50, left: 50, right: 50 }
            });
            
            const chunks = [];
            
            // Collect PDF chunks
            doc.on('data', chunk => chunks.push(chunk));
            doc.on('end', () => resolve(Buffer.concat(chunks)));
            doc.on('error', reject);

            // Add metadata
            doc.info = {
                Title: 'MAD-MAX PDF Document',
                Author: 'MAD-MAX Bot',
                Subject: 'Text to PDF Conversion',
                Keywords: 'pdf, text, MAD-MAX, converter',
                CreationDate: new Date()
            };

            // Add header
            doc.fontSize(20)
               .font('Helvetica-Bold')
               .text('📄 MAD-MAX PDF Document', { align: 'center' })
               .moveDown(0.5);

            doc.fontSize(10)
               .font('Helvetica')
               .text(`Created: ${new Date().toLocaleString()}`, { align: 'center' })
               .moveDown(2);

            // Add content
            doc.fontSize(12)
               .font('Helvetica')
               .text('Content:', { underline: true })
               .moveDown(0.5);

            doc.fontSize(11)
               .font('Helvetica')
               .text(text, {
                    align: 'left',
                    lineGap: 5,
                    paragraphGap: 10,
                    indent: 20,
                    width: 500
               })
               .moveDown(2);

            // Add footer
            const pageWidth = doc.page.width;
            const pageHeight = doc.page.height;
            
            doc.fontSize(9)
               .font('Helvetica-Oblique')
               .text('Generated by MAD-MAX Bot', 50, pageHeight - 50, {
                    align: 'center',
                    width: pageWidth - 100
               });

            // Finalize
            doc.end();

        } catch (error) {
            reject(error);
        }
    });
}